//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class evaluate : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Customer fcustomerID;
        [Association(@"evaluateReferencesCustomer")]
        public Customer customerID
        {
            get { return fcustomerID; }
            set { SetPropertyValue<Customer>(nameof(customerID), ref fcustomerID, value); }
        }
        Product fproductID;
        [Association(@"evaluateReferencesProduct")]
        public Product productID
        {
            get { return fproductID; }
            set { SetPropertyValue<Product>(nameof(productID), ref fproductID, value); }
        }
        string fcontent;
        public string content
        {
            get { return fcontent; }
            set { SetPropertyValue<string>(nameof(content), ref fcontent, value); }
        }
    }

}
