//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class Inventory : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Product fproductID;
        [Association(@"InventoryReferencesProduct")]
        public Product productID
        {
            get { return fproductID; }
            set { SetPropertyValue<Product>(nameof(productID), ref fproductID, value); }
        }
        double fstockQuantity;
        public double stockQuantity
        {
            get { return fstockQuantity; }
            set { SetPropertyValue<double>(nameof(stockQuantity), ref fstockQuantity, value); }
        }
        decimal fpurchase_price;
        public decimal purchase_price
        {
            get { return fpurchase_price; }
            set { SetPropertyValue<decimal>(nameof(purchase_price), ref fpurchase_price, value); }
        }
        decimal fselling_price;
        public decimal selling_price
        {
            get { return fselling_price; }
            set { SetPropertyValue<decimal>(nameof(selling_price), ref fselling_price, value); }
        }
        DateTime fstock_entry_date;
        public DateTime stock_entry_date
        {
            get { return fstock_entry_date; }
            set { SetPropertyValue<DateTime>(nameof(stock_entry_date), ref fstock_entry_date, value); }
        }
    }

}
