//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class Payment : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Customer fcustomerID;
        [Association(@"PaymentReferencesCustomer")]
        public Customer customerID
        {
            get { return fcustomerID; }
            set { SetPropertyValue<Customer>(nameof(customerID), ref fcustomerID, value); }
        }
        Shopping_Cart fshoppingCartID;
        [Association(@"PaymentReferencesShopping_Cart")]
        public Shopping_Cart shoppingCartID
        {
            get { return fshoppingCartID; }
            set { SetPropertyValue<Shopping_Cart>(nameof(shoppingCartID), ref fshoppingCartID, value); }
        }
        string fmethod;
        public string method
        {
            get { return fmethod; }
            set { SetPropertyValue<string>(nameof(method), ref fmethod, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
    }

}
