//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class productGroup : XPObject
    {
        string fcategory_name;
        public string category_name
        {
            get { return fcategory_name; }
            set { SetPropertyValue<string>(nameof(category_name), ref fcategory_name, value); }
        }
        string fclassify;
        public string classify
        {
            get { return fclassify; }
            set { SetPropertyValue<string>(nameof(classify), ref fclassify, value); }
        }
        [Association(@"ProductReferencesproductGroup"), Aggregated]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
    }

}
