//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class SalaryTable : DevExpress.Persistent.BaseImpl.BaseObject
    {
        User fuserID;
        [Association(@"SalaryTableReferencesUser")]
        public User userID
        {
            get { return fuserID; }
            set { SetPropertyValue<User>(nameof(userID), ref fuserID, value); }
        }
        DateTime fyear;
        public DateTime year
        {
            get { return fyear; }
            set { SetPropertyValue<DateTime>(nameof(year), ref fyear, value); }
        }
        DateTime fmonth;
        public DateTime month
        {
            get { return fmonth; }
            set { SetPropertyValue<DateTime>(nameof(month), ref fmonth, value); }
        }
        decimal fhour;
        public decimal hour
        {
            get { return fhour; }
            set { SetPropertyValue<decimal>(nameof(hour), ref fhour, value); }
        }
        [PersistentAlias("ToDecimal([hour]) * [salary] + [bonus] - [deduction]")]
        public decimal totalSalary
        {
            get { return (decimal)(EvaluateAlias(nameof(totalSalary))); }
        }
        decimal fbonus;
        public decimal bonus
        {
            get { return fbonus; }
            set { SetPropertyValue<decimal>(nameof(bonus), ref fbonus, value); }
        }
        decimal fdeduction;
        public decimal deduction
        {
            get { return fdeduction; }
            set { SetPropertyValue<decimal>(nameof(deduction), ref fdeduction, value); }
        }
        decimal fsalary;
        public decimal salary
        {
            get { return fsalary; }
            set { SetPropertyValue<decimal>(nameof(salary), ref fsalary, value); }
        }
    }

}
