//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    [DefaultProperty("invoiceNumber")]
    public partial class Shop_Order : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Customer fcustomerID;
        [Association(@"Shop_OrderReferencesCustomer")]
        public Customer customerID
        {
            get { return fcustomerID; }
            set { SetPropertyValue<Customer>(nameof(customerID), ref fcustomerID, value); }
        }
        Shipping fshippingID;
        [Association(@"Shop_OrderReferencesShipping")]
        public Shipping shippingID
        {
            get { return fshippingID; }
            set { SetPropertyValue<Shipping>(nameof(shippingID), ref fshippingID, value); }
        }
        User fuserID;
        [Association(@"Shop_OrderReferencesUser")]
        public User userID
        {
            get { return fuserID; }
            set { SetPropertyValue<User>(nameof(userID), ref fuserID, value); }
        }
        int finvoiceNumber;
        public int invoiceNumber
        {
            get { return finvoiceNumber; }
            set { SetPropertyValue<int>(nameof(invoiceNumber), ref finvoiceNumber, value); }
        }
        DateTime fdateOrder;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")
]
        public DateTime dateOrder
        {
            get { return fdateOrder; }
            set { SetPropertyValue<DateTime>(nameof(dateOrder), ref fdateOrder, value); }
        }
        string faddress;
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        statictis fstatictisID;
        [Association(@"Shop_OrderReferencesstatictis")]
        public statictis statictisID
        {
            get { return fstatictisID; }
            set { SetPropertyValue<statictis>(nameof(statictisID), ref fstatictisID, value); }
        }
        [Association(@"Shop_Order_DetailReferencesShop_Order"), Aggregated]
        public XPCollection<Shop_Order_Detail> Shop_Order_Details { get { return GetCollection<Shop_Order_Detail>(nameof(Shop_Order_Details)); } }
        [Association(@"Shopping_CartReferencesShop_Order"), Aggregated]
        public XPCollection<Shopping_Cart> Shopping_Carts { get { return GetCollection<Shopping_Cart>(nameof(Shopping_Carts)); } }
    }

}
