//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class Shopping_Cart_Item : DevExpress.Persistent.BaseImpl.BaseObject
    {
        double fquantity;
        public double quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<double>(nameof(quantity), ref fquantity, value); }
        }
        Product fproductID;
        [Association(@"Shopping_Cart_ItemReferencesProduct")]
        public Product productID
        {
            get { return fproductID; }
            set { SetPropertyValue<Product>(nameof(productID), ref fproductID, value); }
        }
        Shopping_Cart fshoppingCartID;
        [Association(@"Shopping_Cart_ItemReferencesShopping_Cart")]
        public Shopping_Cart shoppingCartID
        {
            get { return fshoppingCartID; }
            set { SetPropertyValue<Shopping_Cart>(nameof(shoppingCartID), ref fshoppingCartID, value); }
        }
    }

}
