//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class Supplier : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fMST;
        public string MST
        {
            get { return fMST; }
            set { SetPropertyValue<string>(nameof(MST), ref fMST, value); }
        }
        [Association(@"Warehouse_receiptReferencesSupplier"), Aggregated]
        public XPCollection<Warehouse_receipt> Warehouse_receipts { get { return GetCollection<Warehouse_receipt>(nameof(Warehouse_receipts)); } }
    }

}
