//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class timeKeeping : DevExpress.Persistent.BaseImpl.BaseObject
    {
        User fuserID;
        [Association(@"timeKeepingReferencesUser")]
        public User userID
        {
            get { return fuserID; }
            set { SetPropertyValue<User>(nameof(userID), ref fuserID, value); }
        }
        DateTime fstartTime;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime startTime
        {
            get { return fstartTime; }
            set { SetPropertyValue<DateTime>(nameof(startTime), ref fstartTime, value); }
        }
        DateTime fendTime;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"), DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime endTime
        {
            get { return fendTime; }
            set { SetPropertyValue<DateTime>(nameof(endTime), ref fendTime, value); }
        }
    }

}
