//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    [DefaultProperty("name")]
    public partial class User : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string faddress;
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fphone;
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string fuserName;
        public string userName
        {
            get { return fuserName; }
            set { SetPropertyValue<string>(nameof(userName), ref fuserName, value); }
        }
        string fpassWord;
        public string passWord
        {
            get { return fpassWord; }
            set { SetPropertyValue<string>(nameof(passWord), ref fpassWord, value); }
        }
        [Association(@"Shop_OrderReferencesUser"), Aggregated]
        public XPCollection<Shop_Order> Shop_Orders { get { return GetCollection<Shop_Order>(nameof(Shop_Orders)); } }
        [Association(@"timeKeepingReferencesUser"), Aggregated]
        public XPCollection<timeKeeping> timeKeepings { get { return GetCollection<timeKeeping>(nameof(timeKeepings)); } }
        [Association(@"SalaryTableReferencesUser"), Aggregated]
        public XPCollection<SalaryTable> SalaryTables { get { return GetCollection<SalaryTable>(nameof(SalaryTables)); } }
        [Association(@"Warehouse_receiptReferencesUser"), Aggregated]
        public XPCollection<Warehouse_receipt> Warehouse_receipts { get { return GetCollection<Warehouse_receipt>(nameof(Warehouse_receipts)); } }
    }

}
