//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cnpm_thoitrang.Module.BusinessObjects.thoitrang
{

    public partial class Warehouse_receipt : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Supplier fsupplierID;
        [Association(@"Warehouse_receiptReferencesSupplier")]
        public Supplier supplierID
        {
            get { return fsupplierID; }
            set { SetPropertyValue<Supplier>(nameof(supplierID), ref fsupplierID, value); }
        }
        User fuserID;
        [Association(@"Warehouse_receiptReferencesUser")]
        public User userID
        {
            get { return fuserID; }
            set { SetPropertyValue<User>(nameof(userID), ref fuserID, value); }
        }
        int fnumber;
        public int number
        {
            get { return fnumber; }
            set { SetPropertyValue<int>(nameof(number), ref fnumber, value); }
        }
        double fquantity;
        public double quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<double>(nameof(quantity), ref fquantity, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        [Association(@"import_orderReferencesWarehouse_receipt"), Aggregated]
        public XPCollection<import_order> import_orders { get { return GetCollection<import_order>(nameof(import_orders)); } }
    }

}
